groups:
- name: isc_reserved
  rules:
  - alert: iris_system_alerts
    annotations:
      description: 'WARNING: Removing this rule will disable the handling of InterSystems
        IRIS System Monitor text alerts!'
    expr: (idelta(iris_system_alerts_log[5m]) != 0) or (iris_system_alerts_new > 0)
- name: "1"
  rules:
  - alert: GloRef>50000
    annotations:
      description: High Number of  Global References per second
    expr: iris_glo_ref_per_sec{cluster="1"} > 50000
    labels:
      severity: warning

